export const radOptions = [5, 10, 25, 50, 100, 500];
export const rad2Options = ['mi', 'km'];
export const cidOptions = [
  { value: 1, text: "Airfreight Forwarding" },
  { value: 2, text: "Alcohol" },
  { value: 3, text: "Brokerage" },
  { value: 4, text: "Customs Broker" },
  { value: 5, text: "Cross Border/International" },
  { value: 6, text: "CTPAT Certified" },
  { value: 7, text: "Domestic Freight Forwarder" },
  { value: 8, text: "Household Goods" },
  { value: 9, text: "Freight Bill Audit/Payment" },
  { value: 10, text: "Freight Billing and Collection " },
  { value: 12, text: "Fulfillment" },
  { value: 13, text: "Hazmat/Dangerous Goods" },
  { value: 14, text: "Intermodal Marketing Company" },
  { value: 16, text: "International Freight Forwarder" },
  { value: 17, text: "Less than Truckload" },
  { value: 18, text: "Logistics/Transportation Management" },
  { value: 19, text: "Ocean Transportation Intermediary" },
  { value: 20, text: "Oversize over Dimensional Management" },
  { value: 21, text: "Perishable Commodity Brokerage" },
  { value: 22, text: "TIA Bond" },
  { value: 23, text: "Smartway Certified" },
  { value: 24, text: "Truckload" },
  { value: 25, text: "Warehousing" },
  { value: 26, text: "Bid Development Software/Consulting" },
  { value: 27, text: "Carrier Management/Monitoring" },
  { value: 28, text: "Collection" },
  { value: 29, text: "Computer Systems/Hardware" },
  { value: 30, text: "Consulting" },
  { value: 31, text: "Credit Reporting" },
  { value: 32, text: "Factoring/Financial Services" },
  { value: 33, text: "Freight Matching/Auction" },
  { value: 34, text: "HR Outsourcing/Recruiting/Consulting" },
  { value: 35, text: "Insurance/Risk Management" },
  { value: 36, text: "Intermodal Equipment Provider" },
  { value: 37, text: "Legal Services/Attorney" },
  { value: 38, text: "Freight/Logistics/Transportation Managem..." },
  { value: 39, text: "Merger &amp; Acquisition" },
  { value: 40, text: "Motor Carrier" },
  { value: 41, text: "Public Relations/Marketing" },
  { value: 42, text: "Riggers and Specialized Carriers" },
  { value: 43, text: "Vehicle Tracing/Tracking " },
  { value: 44, text: "Government Freight (GSA)" },
  { value: 45, text: "Government Freight (DOD)" },
  { value: 46, text: "Carrier" },
  { value: 47, text: "Training/Education" },
  { value: 48, text: "Auto Transport Broker" },
  { value: 49, text: "Food/Produce Broker" },
  { value: 50, text: "Women Owned" },
  { value: 51, text: "Minority Owned" },
  { value: 52, text: "Container Drayage" },
  { value: 53, text: "Disaster Recovery/Emergency Preparedness" },
  { value: 54, text: "Fraud Prevention/Assistance" },
  { value: 55, text: "Technology Services" },
];